import { CalendarDays, Flame, RotateCcw, SlidersHorizontal, Sparkles, Trophy, UserRound } from "lucide-react";
import { useSession } from "../../auth/SessionProvider";
import { ProgressBar } from "../../components/ui";
import { BACKGROUNDS, FONTS, useTheme } from "../../theme/ThemeProvider";
import { userProgress } from "../../utils/format";

export function ProfilePage() {
  const { user } = useSession();
  const { backgroundId, fontId, brightness, contrast, setBackgroundId, setFontId, setBrightness, setContrast, resetAppearance } = useTheme();
  if (!user) return null;
  const lastStudy = user.lastTaskCompletedDate ? new Intl.DateTimeFormat(undefined, { month: "long", day: "numeric", year: "numeric" }).format(new Date(user.lastTaskCompletedDate)) : "No completed tasks yet";
  return <div className="page page-narrow"><section className="profile-hero"><div className="profile-avatar"><UserRound size={35} /></div><div><p className="eyebrow">Explorer profile</p><h1>{user.username}</h1><p>Your study journey is built one finished task at a time.</p></div></section><section className="profile-grid"><article className="profile-card profile-level"><div className="card-icon"><Trophy size={21} /></div><p>Current level</p><strong>Level {user.level}</strong><ProgressBar value={userProgress(user.xp)} label={`${user.xp.toLocaleString()} total XP`} /></article><article className="profile-card"><div className="card-icon orange"><Flame size={21} /></div><p>Current streak</p><strong>{user.streak} {user.streak === 1 ? "day" : "days"}</strong><span>Keep the flame going.</span></article><article className="profile-card"><div className="card-icon violet"><Sparkles size={21} /></div><p>Total XP</p><strong>{user.xp.toLocaleString()}</strong><span>XP earned from completed work.</span></article><article className="profile-card"><div className="card-icon green"><CalendarDays size={21} /></div><p>Last task completed</p><strong className="profile-date">{lastStudy}</strong></article></section><section className="appearance-section"><div className="section-header"><div><p className="eyebrow">Make it yours</p><h2><SlidersHorizontal size={21} />Appearance</h2></div><button className="reset-appearance" onClick={resetAppearance}><RotateCcw size={15} />Reset</button></div><div className="appearance-panel"><fieldset><legend>Background image</legend><div className="background-options">{BACKGROUNDS.map((background) => <button key={background.id} className={`background-option ${backgroundId === background.id ? "active" : ""}`} style={{ backgroundImage: `url("${background.image}")` }} onClick={() => setBackgroundId(background.id)} aria-pressed={backgroundId === background.id}><span>{background.label}</span></button>)}</div></fieldset><fieldset><legend>Font</legend><div className="font-options">{FONTS.map((font) => <button key={font.id} className={fontId === font.id ? "active" : ""} style={{ fontFamily: font.body }} onClick={() => setFontId(font.id)} aria-pressed={fontId === font.id}>{font.label}</button>)}</div></fieldset><div className="appearance-sliders"><label><span>Background brightness <strong>{brightness}%</strong></span><input type="range" min="35" max="130" value={brightness} onChange={(event) => setBrightness(Number(event.target.value))} /></label><label><span>Background contrast <strong>{contrast}%</strong></span><input type="range" min="75" max="150" value={contrast} onChange={(event) => setContrast(Number(event.target.value))} /></label></div></div></section></div>;
}
